"""Shared RenQuant contracts and pipeline primitives."""

from .contracts import (
    AcceptanceReport,
    ArtifactManifest,
    DecisionTraceRow,
    LiveRunBundle,
    OOSEvidence,
    PooledMetric,
    RegimeLabel,
    RegimeMetric,
    SCORER_ENTRY_POINT_GROUP,
    Scorer,
    ScorerKindNotRegistered,
    Tier,
    TriadReport,
    VerifiedArtifact,
    load_scorer,
    validate_live_run_bundle,
    validate_manifest_for_leakage_triad,
    validate_regime_params,
)
from .pipeline import (
    Job,
    ParallelTimeoutError,
    Pipeline,
    PipelineResult,
    PipelineStepRecord,
    Task,
    run_parallel,
)
from .purged_cv import (
    CombinatorialPurgedCV,
    PurgedKFold,
    cross_validated_ic,
    cross_validated_ic_cpcv,
    evaluate_fold_ic,
)
from .hurst import compute_hurst, rolling_hurst
from .market_calendar import (
    CalendarUnavailableError,
    NyseSessionCalendar,
    SessionBounds,
    SessionCalendar,
    default_session_calendar,
    is_session,
    last_completed_session,
    previous_session,
    previous_session_from_calendar,
    session_bounds,
    session_key,
    session_keys,
    sessions_between,
)
from .net_safety import FetchBudget, call_with_timeout
from .regime_labels import (
    compute_spy_regime_labels,
    min_across_regimes,
    per_regime_cs_ic,
)
from .training_runs import record_training_run

__all__ = [
    "AcceptanceReport",
    "ArtifactManifest",
    "CalendarUnavailableError",
    "CombinatorialPurgedCV",
    "DecisionTraceRow",
    "Job",
    "LiveRunBundle",
    "NyseSessionCalendar",
    "OOSEvidence",
    "ParallelTimeoutError",
    "Pipeline",
    "PipelineResult",
    "PipelineStepRecord",
    "PooledMetric",
    "PurgedKFold",
    "RegimeLabel",
    "RegimeMetric",
    "SCORER_ENTRY_POINT_GROUP",
    "Scorer",
    "ScorerKindNotRegistered",
    "SessionBounds",
    "SessionCalendar",
    "Task",
    "FetchBudget",
    "Tier",
    "TriadReport",
    "VerifiedArtifact",
    "call_with_timeout",
    "compute_hurst",
    "compute_spy_regime_labels",
    "cross_validated_ic",
    "cross_validated_ic_cpcv",
    "default_session_calendar",
    "evaluate_fold_ic",
    "is_session",
    "last_completed_session",
    "load_scorer",
    "min_across_regimes",
    "per_regime_cs_ic",
    "previous_session",
    "previous_session_from_calendar",
    "record_training_run",
    "rolling_hurst",
    "run_parallel",
    "session_bounds",
    "session_key",
    "session_keys",
    "sessions_between",
    "validate_live_run_bundle",
    "validate_manifest_for_leakage_triad",
    "validate_regime_params",
]
